### ISSUE TITLE
Google Authenticator throwing exception

### ISSUE THREAD

**Issue by srinidhillc** [elibus/j-google-trends-client#2]
Dear Marco,
I tried usng the version which was updated 17 days agao 
j-google-trends-client\releases\org\freaknet\gtrends\client\j-google-trends-client\1.2.1\j-google-trends-client-1.2.1-jar-with-dependencies.jar

and getting the following exception:
org.freaknet.gtrends.client.exceptions.HierarchicalDownloaderException: org.freaknet.gtrends.api.exceptions.GoogleTrendsClientException: org.freaknet.gtrends.api.exceptions.GoogleAuthenticatorException: org.freaknet.gtrends.api.exceptions.GoogleAuthenticatorException: Failed to login!
    at org.freaknet.gtrends.client.HierarchicalDownloader.start(HierarchicalDownloader.java:130)
My userid password works fine when i tried logging into google trends website:
userName=scotttrend12312013
passWord=stockstrends

Please advise me if I need to use other version? ( i was earlier using 1.2.2.SNAPSHOT version, it worked few days later stopped workign with above exception.

I greatly appreciate your help.

Thanks.

**Comment by elibus** [comment]
Fixed in client 1.2.2 and API 1.5

**Comment by srinidhillc** [comment]
Perfect. This worked like a chram. Thank you fpr helping with a fix. 
This API is too good. I recommned anyone who needs to it connect to google trends from java , use this
